blog/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.all_blogs, name='all_blogs'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Blogs(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=240)
    date = models.DateField(blank=False)
    image = models.ImageField(blank=True)
    text = models.TextField(max_length=1000)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Blog"
        verbose_name_plural = "Blogs"

portfolio/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    title = models.CharField(max_length=80)
    description = models.CharField(max_length=240)
    image = models.ImageField()
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Project"
        verbose_name_plural = "Projects"

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blogs
# Create your views here.
def all_blogs(request):
    blogs = Blogs.objects.order_by('-date')
    return render(request, 'blog/all_blogs.html', {'blogs': blogs})

def detail(request, blog_id):
    blog = get_object_or_404(Blogs, pk=blog_id)
    return render(request, 'blog/detail.html', {'blog': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Project
# Create your views here.


def home(request):
    projects = Project.objects.all()
    return render(request, 'portfolio/index.html', {'projects': projects})

blog/templates/blog/all_blogs.html
{% extends 'portfolio/template.html' %}
{% block content %}
    Here are your blogs
    <a href="{% url 'home' %}">Home</a>
    <h3>Adilet has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h3>
    {% for elem in blogs %}
    <a href="{% url 'blog:detail' elem.id %}"><h2> {{ elem.title }} </h2></a>
    <h5> {{ elem.date|date:'M d Y'|upper }}</h5>
    <p> {{ elem.description|truncatechars:100|striptags }} </p>
    {% endfor %}

{% endblock %}

blog/templates/blog/detail.html
{% extends 'portfolio/template.html' %}
{% block content %}
    <h2> {{ blog.title }} </h2> <br>
    {{ blog.date|date:'F jS Y' }}
    <h4>{{ blog.description|safe }}</h4> <br>
    {% if blog.image %}
    <img src="{{ blog.image.url }}" alt="image is not loading"> <br>
    {% endif %}
    <p>{{ blog.text|safe  }}</p> <br>
{% endblock %}

portfolio/templates/portfolio/index.html
{% extends 'portfolio/template.html' %}
{% load static %}



{% block content %}
<div class="container-fluid">
    <div class="row justify-content-center mb-3">
        <div class="col-md-9 text-center">
            <h1>Adilet's Portfolio</h1>
        </div>
    </div>
    <img src="{% static 'portfolio/images/profilpicture.jpg' %}">
    <main>
    <div class="col-md-11">
            <div class="row">
                {% for elem in projects %}
                <div class="col-md-4">
                    <div class="card my-4">
                        {% if elem.url %}
                            <a href="{{ elem.url }}"><img src="{{ elem.image.url }}"></a>
                        {% else %}
                            <img src="{{ elem.image.url }}">
                        {% endif %}
                        <div class="textinside">
                            <h5> {{ elem.title }} </h5>
                            <p> {{ elem.description }} </p>
                        </div>
                    </div>
                </div>

                {% empty %}
                <div class="else">
                    <h3>Unfortunately, there are no items founded... Probably, author didn't chose category, so try checking category 'all' or come back to site later.</h3>
                    <h1>...</h1>
                </div>
                {% endfor %}
            </div>
    </div>
    </main>
</div>

{% endblock %}

portfolio/templates/portfolio/template.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Adilet's Portfolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'portfolio/css/main.css' %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </head>
  <body>
  <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% static 'portfolio/images/presentationHackathon.pdf' %}">Resume</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Contacts
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="https://www.instagram.com/adilet.exe/">Instagram</a></li>
            <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="https://github.com/adiletexe">GitHub</a></li>
            <li><a class="dropdown-item" href="https://www.linkedin.com/in/adilet-aussarbekov-27b264247/">Linkedin</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'blog:all_blogs' %}">Blogs</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
  </nav>
    {% block content %} {% endblock %}
  </body>
</html>